---

- name: install nfs-utils
  yum:
    name: nfs-utils
    state: present

- name: create mount point
  file:
    path: /home/vagrant/mnt
    state: directory
    


- name: Mount an NFS volume
  mount:
    src: 192.168.121.10:/home/vagrant/nfs
    path: /home/vagrant/mnt
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs

- name: make a persistant mount
  lineinfile:
    path: /etc/fstab
    line: 192.168.121.10:/home/vagrant/nfs    /home/vagrant/mnt   nfs defaults 0 0  
    
      


