
---

- name: set selinux on permissive
  shell: setenforce 0 && sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config


- name: Disabling Swap on all nodes
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

#- name: install some required packages
#  yum:
#    name: "{{required_packages}}"
#    state: present


    
- name: creating a repo file for docker 
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: touch

- name: adding repo details in docker repo file
  copy:
    src: files/repo_docker.txt
    dest: /etc/yum.repos.d/docker-ce.repo

- name: installing docker
  yum:
    name: docker
    state: present  

- name: start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: adding user to docker group
  user:
    name: vagrant
    groups: dockerroot
    append: yes  





